import Link from "next/link";
import "./globals.css";
import { useEffect, useState } from "react";
import { Control } from "./Control";

export const metadata = {
  title: "Welcome!",
  description: "Generated by egoing",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const resp = await fetch("http://localhost:9999/topics", {
    cache: "no-cache",
  });
  const topics = await resp.json();
  return (
    <html lang="en">
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <input type="text" placeholder="search" />
        <ol>
          {/* @ts-ignore */}
          {topics.map((t) => {
            return (
              // @ts-ignore
              <li key={t.id}>
                {/* @ts-ignore */}
                <Link href={"/read/" + t.id}>{t.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control></Control>
      </body>
    </html>
  );
}
