"use client";
import Link from "next/link";
import "./globals.css";
import { useEffect, useState } from "react";

export const metadata = {
  title: "Welcome!",
  description: "Generated by egoing",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [topics, setTopics] = useState([]);
  console.log("🚀 ~ file: layout.tsx:17 ~ topics:", topics);
  useEffect(() => {
    fetch("http://localhost:3000/api/topics")
      .then((resp) => resp.json())
      .then((result) => {
        console.log("result", result);
        setTopics(result);
      });
  }, []);
  return (
    <html lang="en">
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <input type="text" placeholder="search" />
        <ol>
          {topics.map((t) => {
            return (
              // @ts-ignore
              <li key={t.id}>
                {/* @ts-ignore */}
                <Link href={"/read/" + t.id}>{t.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <ul>
          <li>
            <Link href="/create">create</Link>
          </li>
          <li>
            <Link href="/update/1">update</Link>
          </li>
          <li>
            <input type="button" value="delete" />
          </li>
        </ul>
      </body>
    </html>
  );
}
